'use strict';

module.exports = [
	{ cmd: 'wave', params: [ 'C_PLAYER\\EXP_WAVE' ] },
	{ cmd: 'victory', params: [ 'C_PLAYER\\VICTORY01' ] },
	{ cmd: 'agree', params: [ 'SOCIAL\\AGREE_UBO' ] },
	{ cmd: 'disagree', params: [ 'SOCIAL\\DISAGREE_UBO' ] },
	{ cmd: 'laugh', params: [ 'C_PLAYER\\LAUGH_02' ] },
	{ cmd: 'cry', params: [ 'NPC_GENERIC\\REAC_CRY' ] },
	{ cmd: 'finger', params: [ 'C_PLAYER\\EXP_FINGER' ] },
	{ cmd: 'give', params: [ 'C_PLAYER\\GEN_GIVE' ] },
	{ cmd: 'recieve', params: [ 'C_PLAYER\\GEN_RECIEVE' ] },
	{ cmd: 'pickup', params: [ 'C_PLAYER\\PICKUP' ] },
	{ cmd: 'throw', params: [ 'C_PLAYER\\THROW' ] },
	{ cmd: 'open', params: [ 'C_PLAYER\\OPEN_DOOR_EASY' ] },
	{ cmd: 'impressed', params: [ 'NPC_GENERIC\\GEN_IMPRESSED02' ] },
	{ cmd: 'stop', params: [ 'NPC_GENERIC\\HALL_SIGNAL_STOP' ] },
	{ cmd: 'comeon', params: [ 'NPC_GENERIC\\REAC_COMEON' ] },
	{ cmd: 'dontmess', params: [ 'NPC_GENERIC\\REAC_DONTMESS' ] },
	{ cmd: 'donthurt', params: [ 'NPC_GENERIC\\REAC_DONTHURT' ] },
	{ cmd: 'slitthroat', params: [ 'NPC_GENERIC\\REAC_SLIT_THROAT' ] },
	{ cmd: 'bringit', params: [ 'NPC_GENERIC\\REAC_BRING_IT' ] },
	{ cmd: 'coward', params: [ 'NPC_GENERIC\\REAC_COWAR' ] },
	{ cmd: 'goingdown', params: [ 'NPC_GENERIC\\REAC_GOIN_DWN' ] },
	{ cmd: 'hair', params: [ 'NPC_GENERIC\\BATH_HAIR' ] },
	{ cmd: 'zit', params: [ 'NPC_GENERIC\\BATH_ZIT' ] },
	{ cmd: 'eatcandy', params: [ 'C_PLAYER\\EAT_CANDY' ] },
	{ cmd: 'peedance', params: [ 'F_NERDS\\ALG_PEEDANCE' ] },
	{ cmd: 'disgusted', params: [ 'C_PLAYER\\REACT_DISGUSTED' ] },
	{ cmd: 'fail', params: [ 'MINI_REACT\\MG_FAIL_LOW_1' ] },
	{ cmd: 'point', params: [ 'NIS\\GARY_1-04_51_V1' ] },
	{ cmd: 'checkshit', params: [ 'NPC_GENERIC\\CHECK_SHITSHOE' ] },
	{ cmd: 'shitstomp', params: [ 'NPC_GENERIC\\SHITSTOMP_IN' ] },
	{ cmd: 'antic', params: [ 'RUSSELL\\BG_ANTIC', 0, 1, 0, 0, 1.6667, 0.7500, -1.0000, -1.0000, 0, 0 ] },
	{ cmd: 'picklock', params: [ 'MINI_LOCK\\PICKLOCK_L' ] },
	{ cmd: 'forget', params: [ 'NPC_GENERIC\\HARAS_FORGET' ] },
	{ cmd: 'boo', params: [ 'F_GIRLS\\FM_BOO_A' ] },
	{ cmd: 'blowkiss', params: [ 'F_GIRLS\\FM_BLOWKISS' ] },
	{ cmd: 'freakout', params: [ 'F_GIRLS\\F_FREAKOUT' ] },
	{ cmd: 'girlclap', params: [ 'F_GIRLS\\FM_CLAP' ] },
	{ cmd: 'girlhop', params: [ 'F_GIRLS\\FM_HOPREACT' ] },
	{ cmd: 'impatientgirl', params: [ 'F_GIRLS\\SXY_IMPATIENT' ] },
	{ cmd: [ 'celeb', 'celebrate' ], params: [ 'MINI_REACT\\MG_CELEB_HI_3' ] },
	{ cmd: 'shakefist', params: [ 'NPC_GENERIC\\SHAKE_FIST' ] },
	{ cmd: 'joinme', params: [ 'NPC_GENERIC\\JV_JOINME' ] },
	{ cmd: 'mascotpass', params: [ 'NPC_MASCOT\\MASCOT_PASS' ] },
	{ cmd: 'mascotfail', params: [ 'NPC_MASCOT\\MASCOT_FAIL' ] },
	{ cmd: 'mascotflub', params: [ 'NPC_MASCOT\\MASCOT_FLUB' ] },
	{ cmd: 'mascotdance1', params: [ 'NPC_MASCOT\\MASCOT_DANCE_A' ] },
	{ cmd: 'mascotdance2', params: [ 'NPC_MASCOT\\MASCOT_DANCE_B' ] },
	{ cmd: 'mascotdance3', params: [ 'NPC_MASCOT\\MASCOT_DANCE_C' ] },
	{ cmd: 'mascotdance4', params: [ 'NPC_MASCOT\\MASCOT_DANCE_D' ] },
	{ cmd: 'rig', params: [ '4_06BIGGAME\\CONTROLBOX_RIG' ] },
	{ cmd: 'scratchhead', params: [ 'PLAYERIDLES\\SCRATCHHEAD_01' ] },
	{ cmd: 'scratchpit', params: [ 'PLAYERIDLES\\SCRATCHPIT_01' ] },
	{ cmd: 'scratchballs', params: [ 'NPC_GENERIC\\J_SCRATCH' ] },
	{ cmd: 'scratcharse', params: [ 'PLAYERIDLES\\SCRATCHARSE_01' ] },
	{ cmd: 'spit', params: [ 'NPC_GENERIC\\SPIT_1' ] },
	{ cmd: 'smoke', params: [ 'MINICHEM\\MINIC_REACT_SMOKE' ] },
	{ cmd: 'spray', params: [ 'C_PLAYER\\SPRAY_GIANT' ] },
	{ cmd: 'warning', params: [ 'PF_BASIC_A\\WARNING' ] },
	{ cmd: 'taunt', params: [ 'S_PLAY\\P_TAUNT_01', 'Upperbody_All', 0, 0, 0, -1.0000, 1.0000, -1.0000, -1.0000, 1, 0 ] },
	{ cmd: 'aloof', params: [ 'C_PLAYER\\REACT_ALOOF' ] },
	{ cmd: 'chat', params: [ 'CHAT\\CIVM_TK_1', 'Upperbody_All', 0, 2, 0, -1.0000, 1.0000, -1.0000, -1.0000, 1, 0 ] },
];
